### ISSUE TITLE
Does this work with express-graphql or replace it?

### ISSUE THREAD

**Issue by Hongbo-Miao** [enisdenjo/graphql-transport-ws#12]
Thanks @enisdenjo for this awesome package!

A question, does this work with `express-graphql` or replace it?

Before I had something like

```js
import { graphqlHTTP } from 'express-graphql';

const graphQLMiddleware = graphqlHTTP({
  context: {
    dataLoaders: {
      user: userDataLoader,
    },
  },
  schema,
});
```

However, when I write code like this, it does not supports `context`:

```js
import { createServer } from 'graphql-transport-ws';

createServer(
  {
    context: { // <- not support here
      dataLoaders: {
        user: userDataLoader,
      },
    },
    schema,
  },
  {
    server,
    path: '/graphql',
  }
);
```

**Comment by Hongbo-Miao** [comment]
I think in able to work with `express-graphql`, I can use `express-graphql` for query and mutation schema, and `graphql-transport-ws` for subscription schema only. Let me try.

**Comment by Hongbo-Miao** [comment]
Hmm, still no luck. Got many "101 Switching Protocals" on client side...

<img width="687" alt="image" src="https://user-images.githubusercontent.com/3375461/93400718-01b9a700-f8b3-11ea-9e36-633f5d2f7ab8.png">

**Comment by enisdenjo** [comment]
Hey @Hongbo-Miao, you're very welcome!

Thank you for asking this question. In short - **yes**, this library supports `express-graphql` and it should fulfil all your requirements.

On the side note, `101 Switching Protocols` is good. This indicates that the HTTP handshake went well and the browser is "switching" to the WebSocket Protocol.

Back to your problem - we don't support specifying the context during the server creation (I opened a separate issue here #13); **however**, you can still inject it in the `execute` and/or `subscribe` operations. Also, you **can** indeed perform all 3 operations through WebSocket.

Here is how:

```ts
// server.ts

import http from 'http';
import express from 'express';
import { graphqlHTTP } from 'express-graphql';
import { createServer } from 'graphql-transport-ws';
import { execute } from 'graphql';

// your schema
const schema = { ... };

// your context
const context = {
  dataLoaders: {
    user: userDataLoader,
  },
};

// create express and middleware
const app = express();
app.use(
  '/graphql',
  graphqlHTTP({
    schema,
    context,
  }),
);

// create a http server using express
const server = http.createServer(app);

// listen on port 7070
server.listen(7070, () => {
  // and create a WebSocket server on the same port
  createServer(
    {
      schema,
      execute: (args) =>
        execute({
          ...args,
          context, // inject the context
        }),
      subscribe: (args) =>
        subscribe({
          ...args,
          context, // inject the context
        }),
    },
    {
      server,
      path: '/graphql', // you can even use the same path (just use the `ws` scheme)
    },
  );
});
```

```ts
// client.ts

const client = createClient({
  url: 'ws://localhost:7070/graphql',
});

// query
client.subscribe( 
  {
    query: `{ sayHi }`,
  },
  {
    next: (data) => {
      console.log(data);
    },
    error: (error) => {
      console.error(error);
    },
    complete: () => {
      console.log('said hi');
    },
  },
);

// subscription
client.subscribe( 
  {
    query: `subscriptions { planetsInOurSolarSystem }`,
  },
  {
    next: (data) => {
      // will be called 8 times
      console.log(data);
    },
    error: (error) => {
      console.error(error);
    },
    complete: () => {
      console.log('no more planets');
    },
  },
);
```

**Comment by enisdenjo** [comment]
I added a server usage with `Express GraphQL` recipe 👉 https://github.com/enisdenjo/graphql-transport-ws/commit/680673ef8c86efe70cba3af2e27dc28581ff07bd.

**Comment by Hongbo-Miao** [comment]
Thanks @enisdenjo for the explaining!

Oh now I get it, with `graphql-transport-ws`, it can provide query and mutation on `ws` or `wss` protocal.
And thanks for the `context` method!

I succeed on the demo using Schema Definition Language with `buildSchema`, but my case actually failed on using GraphQLSchema object way, since it is different topic, I will ask in another ticket.
