### ISSUE TITLE
How to use in GraphQL.js GraphQLSchema object way?

### ISSUE THREAD

**Issue by Hongbo-Miao** [enisdenjo/graphql-transport-ws#15]
This is my client:

```ts
const client = createClient({
  url: 'wss://localhost:5000/graphql',
});

client.subscribe(
  {
    query: 'subscription { greeting }',
  },
  {
    next: (data) => {
      console.log('data', data);
    },
    error: (error) => {
      console.error('error', error);
    },
    complete: () => {
      console.log('no more greetings');
    },
  }
);
```

I succeed by GraphQL Schema Definition Language way just like the demo in readme (I only changed `greetings` to `greeting`). Got `101 Switching Protocols`. And the client will print out the `greeting` five times in the browser console. 

Server (Succeed version)

```ts
const schema = buildSchema(`
  type Subscription {
    greeting: String
  }
`);

// The roots provide resolvers for each GraphQL operation
const roots = {
  subscription: {
    greeting: async function* sayHiIn5Languages() {
      for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
        yield { greeting: hi };
      }
    },
  },
};

createServer(
  {
    schema,
    execute,
    subscribe,
    roots,
  },
  {
    server,
    path: '/graphql',
  }
);
```

However, I failed on GraphQL.js GraphQLSchema object way. Got `101 Switching Protocols`. But the client never prints out the `greeting` in the browser console.

Server (Failed version)

```ts
import { execute, subscribe, GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import { createServer } from 'graphql-transport-ws';

const GreetingGraphQLType = new GraphQLObjectType({
  name: 'Greeting',
  fields: {
    greeting: { type: GraphQLString },
  },
});

const subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: {
    greeting: {
      type: GreetingGraphQLType,
      resolve: async function* sayHiIn5Languages() {
        for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
          yield { greeting: hi };
        }
      },
    },
  },
});

const schema = new GraphQLSchema({
  subscription,
});

createServer(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server,
    path: '/graphql',
  }
);
```

Any idea? Thanks

**Comment by enisdenjo** [comment]
You must use the `subscribe` field in the `greeting` definition to emit events.

Check this excerpt from the tests out: https://github.com/enisdenjo/graphql-transport-ws/blob/259a8639a1bb331dedb8c51ea75d7fe1409875d1/src/tests/fixtures/simple.ts#L53-L64

`subscribe` returns an async iterator for emitting events. These events are then fed to the optional `resolve` field of the same definition to manipulate the event data before sending it to the world.

**Comment by enisdenjo** [comment]
To answer the question of the renamed title, here is a full example:

https://github.com/enisdenjo/graphql-transport-ws/blob/259a8639a1bb331dedb8c51ea75d7fe1409875d1/src/tests/fixtures/simple.ts#L15-L67

Hope this helps!

**Comment by Hongbo-Miao** [comment]
Thanks @enisdenjo for the guide!

I updated to this, I am using `setInterval`, and I expected the code will send `Bonjour` every 1 second. But client still didn't get anything. Did I do something wrong? Thanks

```ts
import { execute, subscribe, GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import { createServer } from 'graphql-transport-ws';
import { PubSub } from 'graphql-subscriptions';

const GreetingGraphQLType = new GraphQLObjectType({
  name: 'Greeting',
  fields: {
    greeting: { type: GraphQLString },
  },
});

const pubsub = new PubSub();

const subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: {
    greeting: {
      type: GraphQLGreeting,
      resolve: (source) => {
        if (source instanceof Error) {
          throw source;
        }
        return source.greeting;
      },
      subscribe: () => {
        return pubsub.asyncIterator('greeting');
      },
    },
  },
});

setInterval(() => {
  pubsub.publish('greeting', {
    greeting: 'Bonjour',
  });
}, 1000);

const schema = new GraphQLSchema({
  subscription,
});

createServer(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server,
    path: '/graphql',
  }
);
```

**Comment by enisdenjo** [comment]
Hmm, from the looks of it that should work.

Can you make a repro?

**Comment by Hongbo-Miao** [comment]
Sure, I will!

**Comment by enisdenjo** [comment]
Ahh, I got it!

First of all you're using a `GraphQLGreeting` type which **does not exist**. I guess you wanted to use the `GreetingGraphQLType` you made above the schema.

Besides that, your schema looks like this:
```gql
type Greeting {
  greeting: String
}

type Subscription {
  greeting: Greeting
  # 👆 resolves to:
  # greeting {
  #   greeting: String
  # }
  # greeting inside a greeting 😅
}
```

Try changing the schema to:
```ts
const subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: {
    greeting: {
      type: GraphQLString, // 👈  changed
      resolve: (source) => {
        if (source instanceof Error) {
          throw source;
        }
        return source.greeting;
      },
      subscribe: () => {
        return pubsub.asyncIterator('greeting');
      },
    },
  },
});
```

**Comment by Hongbo-Miao** [comment]
Right, fixed the typo, I was planning to use `GreetingGraphQLType`, changed to `GraphQLString`, still no help... Will further dig in.

**Comment by enisdenjo** [comment]
There must be something wrong in your codebase. The fixture against all server tests are run for this lib uses the `GraphQLSchema` way of constructing the schema.

If you make a repro, I would be happy to look into it!

**Comment by Hongbo-Miao** [comment]
Hi @enisdenjo I found the issue!

Remember in [previous ticket](https://github.com/enisdenjo/graphql-transport-ws/issues/12), I use **express-graphql** for query and mutation, only use **graphql-transport-ws** for subscription. So I have two schema: `queryMutationSchema` and `subscriptionSchema`.

I checked browser got the error 

> Connection Closed: 4400 Query root type must be provided.

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/3375461/93485860-1d19c600-f936-11ea-8b4c-4fb00f0ca411.png">

As long as I provide a dummy query in `subscriptionSchema`, it works now!

Found the solution here: https://github.com/ardatan/graphql-tools/issues/764#issuecomment-419556241

**Comment by enisdenjo** [comment]
Cool, I learned something new too. 😁

Glad you got it working!

**Comment by Hongbo-Miao** [comment]
Posted full solution here to help future people save some time.


```ts
import { execute, subscribe, GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import { createServer } from 'graphql-transport-ws';
import { PubSub } from 'graphql-subscriptions';

const pubsub = new PubSub();

const subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: {
    greeting: {
      type: GraphQLString,
      resolve: (source) => {
        if (source instanceof Error) {
          throw source;
        }
        return source.greeting;
      },
      subscribe: () => {
        return pubsub.asyncIterator('greeting');
      },
    },
  },
});

const query = new GraphQLObjectType({
  name: 'Query',
  fields: {
    dummy: {
      type: GraphQLString,
      resolve: () => {
        return 'dummy';
      },
    },
  },
});

const schema = new GraphQLSchema({
  query,
  subscription,
});

setInterval(() => {
  pubsub.publish('greeting', {
    greeting: 'Bonjour',
  });
}, 1000);

createServer(
  {
    schema,
    execute,
    subscribe,
  },
  {
    server,
    path: '/graphql',
  }
);
```

**Comment by enisdenjo** [comment]
Awesome! However, this is an issue with the `express-graphql` lib so I wouldn't raise confusion by adding this mitigation to the readme recipes.

**Comment by Hongbo-Miao** [comment]
Oh @enisdenjo no, this is not related with **express-graphql**, it is related with **graphql**.

**Comment by Hongbo-Miao** [comment]
Confirmed, if you remove the query in your GraphQL Schema Definition Language way demo, it shows same error. So it is related with **graphql** not **express-graphql**.

**Comment by enisdenjo** [comment]
Oh, I misread. Even in that case, the issue is about about having a _malformed_ schema.

The official [GraphQL spec, under Root Operation Types](http://spec.graphql.org/June2018/#sec-Root-Operation-Types) states:
>A schema defines the initial root operation type for each kind of operation it supports: query, mutation, and subscription; this determines the place in the type system where those operations begin.
>
>The query root operation type must be provided and must be an Object type.

In essence, your GraphQL schema **must** have the query operation provided in the root; otherwise you're not GraphQL compliant.

**Comment by Hongbo-Miao** [comment]
Yeah, that is correct.

**Comment by Hongbo-Miao** [comment]
Oh, I was suggestion adding GraphQLSchema object way to readme.
However, I guess it is fine, since people would find here : )

**Comment by enisdenjo** [comment]
Aha, now I follow. I use the schema parsing for the sake of simplicity. I try to bring more focus on the lib itself, not the semantics of GraphQL. 😄

**Comment by Hongbo-Miao** [comment]
Totally make sense 😀
