### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by Hongbo-Miao** [enisdenjo/graphql-transport-ws#25]
**Screenshot**
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/3375461/95010233-3c189780-065a-11eb-9079-784658418e9f.png">

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/3375461/95010228-2d31e500-065a-11eb-9e4f-840dbd6d08f1.png">

**Expected Behaviour**
I expected the connection was created successful.

**Actual Behaviour**
On localhost, all browsers succeed.
In production, 

- For Firefox, feels 90% time failed. It keeps reconnecting. Tested on Firefox version 79.0, 81.0, and 83.0a1
- For Chrome, most time succeed, but still failed a couple of times.
- For Safari, I haven't seen it failed because of this connection error so far.

The errors are like these in Firefox:

> Firefox can’t establish a connection to the server at wss://www.hongbomiao.com/graphql. 2.2c591de4.chunk.js:2:134796
> The connection to wss://www.hongbomiao.com/graphql was interrupted while the page was loading.

> Firefox can’t establish a connection to the server at wss://www.hongbomiao.com/graphql.

or like this in Chrome:

> WebSocket connection to 'wss://www.hongbomiao.com/graphql' failed: WebSocket is closed before the connection is established.

**Debug Information**
Help us debug the bug? Sure.
I added a ping pong subscription demo by https://github.com/Hongbo-Miao/hongbomiao.com/pull/965
If you open the https://www.hongbomiao.com in Firefox, you will most likely to see the error.

**Further Information**
This might be helpful
https://stackoverflow.com/questions/14140414/websocket-was-interrupted-while-page-is-loading-on-firefox-for-socket-io

**Comment by enisdenjo** [comment]
I cant seem to reproduce the issue for myself. I tried with Chrome, Firefox and Safari - they all connected without problems, even after many refreshes; and kept the connection for indefinitely.

This does not look like a library problem through, it might have something to do with your server setup. Maybe something with TLS? The provided Firefox screenshot shows a crossed out lock sign on the WS connection attempts.

**Comment by Hongbo-Miao** [comment]
Thanks @enisdenjo for looking into this.
I will close for now. If I found anything, I will report back!

**Comment by Hongbo-Miao** [comment]
Just report back. I don't which version might potentially fixed it.
But after upgrading to version 1.13.1. I can confirm the Firefox issue disappeared. Thanks!
