### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by sibelius** [enisdenjo/graphql-transport-ws#27]
Can we have some logging? like koa logger? like this:

![image](https://user-images.githubusercontent.com/2005841/96307292-c60c1d00-0fd7-11eb-9aad-fe4cd1d0c6ae.png)

I think it would be cool to show:
- [ ] show messages received
- [ ] show messages sent
- [ ] show GraphQL operation info? (operation name ?)

**Comment by n1ru4l** [comment]
I also agree!  Having a snippet in the README for getting started would be awesome! People can then adjust it to their own needs as they wish.

**Comment by enisdenjo** [comment]
adding a good, versatile, logging system is not a straight forward task, you have to keep the following in mind:
- Use `console.log`?
  - Not versatile. Can pollute the console with mixed logs. Not in sync with a potential custom logging system (which almost every GQL server offers). Has to be disabled/enabled.
- Pass in a custom logger?
  - Have to "pollute" the lib by injecting the logger calls in various locations. Never-ending task - you have to rely on the lib itself to add support for the logs you want to add.

I am not so keen on adding a logging system to the lib. This lib is intended to be **another tool in your tool-belt**, meaning - you have to provide your own logging implementation _on top of the lib_.

Having the reasoning above in mind, I'd like to avoid logging from within the lib. Please do argument your standpoint, I am open for discussing this.

Furthermore, not integrating a logger **does not mean**  that you cannot extend the lib to log all the details you have requested! Here's how you'd go by:

```ts
import { createServer, ServerOptions } from 'graphql-transport-ws';

function createServerWithLogger({
  execute,
  subscribe,
  onConnect,
  onComplete,
  ...options
}: ServerOptions) {
  createServer(
    {
      ...options,
      execute: async (args) => {
        console.debug('Execute', args);
        const result = await execute(args);
        console.debug('Execute result', result);
        return result;
      },
      subscribe: async (args) => {
        console.debug('Subscribe', args);
        const subscriptionOrResult = await subscribe(args);

        // single result
        if (!isAsyncIterable(subscriptionOrResult)) {
          console.debug('Subscribe result', subscriptionOrResult);
          return subscriptionOrResult;
        }

        // emissions
        return (async function* () {
          for await (const result of subscriptionOrResult) {
            console.debug('Subscribe emitted result', result);
            yield result;
          }
        })();
      },
      onConnect: (ctx) => {
        console.debug('Connect', ctx);
        if (onConnect) {
          return onConnect(ctx);
        }
        return true;
      },
      onComplete: (ctx, msg) => {
        console.debug('Complete', { ctx, msg });
        if (onComplete) {
          onComplete(ctx, msg);
        }
      },
    },
    websocketOptionsOrServer,
  );
}
```

The example from above will log:
- Connection attempts
- Execution request
- Execution result
- Subscription request
- Subscription result(s)
- Operation completions

**Comment by n1ru4l** [comment]
@enisdenjo I guess your snippet would be a nice addition to the recipe section?

**Comment by enisdenjo** [comment]
Please re-open this issue (or open a new one) if you think that the server usage with console logging recipe in the readme is lacking or you want to discuss my statement on internal logging from [the comment above](https://github.com/enisdenjo/graphql-transport-ws/issues/27#issuecomment-711986788).
