### ISSUE TITLE
should the client be notified that the server schema is missing?

### ISSUE THREAD

**Issue by n1ru4l** [enisdenjo/graphql-transport-ws#31]
### Story

I just checked the test cases and noted that the server sends information to the client that the schema is unavailable.
I have concerns that this information should not be leaked to clients in a non-development environment. The client should rather get an unexpected error occurred type of message.

**Comment by enisdenjo** [comment]
Yeah, leaking sensitive information through errors is not ideal. I did leave a TODO though:

https://github.com/enisdenjo/graphql-transport-ws/blob/50a7e0f94013b88f62e84b21247c711bca59c15c/src/server.ts#L317-L321

Setting the close reason to a fixed value will mask all internal server errors.

**Comment by n1ru4l** [comment]
We could choose whether to send a unexpected error message or detailed message based on `process.env.NODE_ENV`. Show detailed message if it equals to `"development"`, otherwise the generic internal error message.

**Comment by enisdenjo** [comment]
I'd say thats fair.
