### ISSUE TITLE
documentation of how to handle Authorization

### ISSUE THREAD

**Issue by sibelius** [enisdenjo/graphql-transport-ws#36]
### Story

I'm want to be able to send user authorization token that can modify the GraphQL context

---
When using `subscriptions-transport-ws` I could generate the GraphQL Context using the `onConnect` helper

https://github.com/sibelius/relay-workshop/blob/master/packages/server/src/index.ts#L30

```jsx
import { SubscriptionServer } from 'subscriptions-transport-ws';

SubscriptionServer.create(
    {
      onConnect: async (connectionParams: ConnectionParams) => {
        const { user } = await getUser(connectionParams?.authorization);

        return getContext({ user });
      },
      // eslint-disable-next-line
      onDisconnect: () => console.log('Client subscription disconnected!'),
      execute,
      subscribe,
      schema,
    },
    {
      server,
      path: '/subscriptions',
    },
  );
```

When using this package, we need to pass `context` on server creating that we won't be able to modify context based on use authorization token

**Comment by enisdenjo** [comment]
You can simply use the [`onSubscribe`](https://github.com/enisdenjo/graphql-transport-ws/blob/master/docs/interfaces/_server_.serveroptions.md#onsubscribe) and inject your context before GraphQL execution. Here's how:
```ts
import { createServer } from 'graphql-transport-ws';

createServer(
  {
    schema,
    execute,
    subscribe,
    onSubscribe: async (ctx, _msg, args) => {
      const { user } = await getUser(ctx.connectionParams?.authorization);
      return [{ ...args, contextValue: await getContext({ user }) }];
    },
  },
  {
    server,
    path: '/graphql',
  },
);
```

or if you want to get the context once [`onConnect`](https://github.com/enisdenjo/graphql-transport-ws/blob/master/docs/interfaces/_server_.serveroptions.md#onconnect) and just reuse it, here is how you'd go by:

```ts
import { createServer } from 'graphql-transport-ws';

const authorizedContexts: Record<string, unknown> = {};

createServer(
  {
    schema,
    execute,
    subscribe,
    onConnect: async (ctx) => {
      if (typeof ctx.connectionParams?.authorization !== 'string'){
        return false;
      }

      const { user } = await getUser(ctx.connectionParams?.authorization);
      authorizedContexts[ctx.connectionParams.authorization] = await getContext({ user });
      return true;
    },
    onSubscribe: (ctx, _msg, args) => {
      return [
        {
          ...args,
          contextValue: authorizedContexts[ctx.connectionParams?.authorization],
        },
      ];
    },
  },
  {
    server,
    path: '/graphql',
  },
);
```

**Comment by enisdenjo** [comment]
I personally perform authorization on every subscription request (in `onSubscribe`). In cases where you're using token based auth, running a check on every operation request guarantees expiry detection or malicious manipulation.

**Comment by sibelius** [comment]
should this be another recipe?

**Comment by enisdenjo** [comment]
I wouldnt say so. It really is that simple and everyone has their own take on authorization. Let the minds go free 😉 .

**Comment by enisdenjo** [comment]
But we could showcase how to inject a custom context for GraphQL, a PR is always welcome 😄 .

**Comment by tautvilas** [comment]
@enisdenjo thanks for this great library. I can not get onSubscribe context params working though. I see that the API has changed. I am trying to do this now:

`onSubscribe: async (ctx, message): Promise<ExecutionArgs> => {
      // console.log('SUBSCRIBE', ctx.connectionParams);
      return { contextValue: ctx.connectionParams, schema, document: null };
    }`

However if I add this code in onSubscribe the subscription itself does not happen. Am I missing something? Is there a way to inject context without passing all the ExecutionArgs? It seems a bit complicated to return whole graphql ExecutionArgs  in order to pass context.

**Comment by enisdenjo** [comment]
Hey @tautvilas,

you're absolutely welcome! 

Straight to business, you are missing the `document` field. TypeScript should be complaining too though...

[Complete and valid execution arguments are expected from you when returning custom ones from the `onSubscribe`.](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/_server_.serveroptions.md#onsubscribe) Validation and all necessary steps for preparing the exec args are on your side, so make sure that the returned args have everything the execution part needs.

**Comment by enisdenjo** [comment]
This is a conscious decision because it allows you to apply optimizations (like executing some rules exclusively or trusting the client implicitly) or simply have control of when the validation happens when you introduce a custom implementation.

**Comment by enisdenjo** [comment]
If you find it helpful, there is a "Server usage with custom dynamic GraphQL arguments and validation" recipe in the readme. It should help you get started.

**Comment by tautvilas** [comment]
Thanks for quick response!

I have tried to replicate the recipe you mentioned, but now I am stuck on the part that msg format is not the same like in recipe. In my case the msg is:
```
{
  id: '8b5311ab-f385-4614-92dd-d657d661b0a9',
  type: 'subscribe',
  payload: { query: 'subscription { verificationPassed }' }
}
```
in the recipe should have these fields:
```
const args = {
        schema,
        contextValue: getDynamicContext(ctx, msg),
        operationName: msg.payload.operationName,
        document: parse(msg.payload.operationName),
        variableValues: msg.payload.variables,
      };
```
why could I be missing the operationName?

**Comment by enisdenjo** [comment]
Well, you have no `operationName` field in the message payload. 😄

**Comment by tautvilas** [comment]
I think I finally got it. The reason I got really confused because there is a bug in the recipe (I think). It should be:
```
operationName: msg.payload.operationName,
document: parse(msg.payload.query),
```
The recipe says that operationName has to be parsed and not query

**Comment by enisdenjo** [comment]
Ah! You're absolutely right. Completely missed that... Fixed it here https://github.com/enisdenjo/graphql-ws/commit/222a7967e439fb52b8f988137146f8924458843c.

Thanks for the insight!

**Comment by ollydixon** [comment]
None of the solutions here seem to pass the TypeScript test, seems they are returning the wrong information. 

Any ideas here?

<img width="1091" alt="Screenshot 2022-04-14 at 17 07 26" src="https://user-images.githubusercontent.com/6940726/163419754-ed1fbeff-1c38-4dfb-8fd0-16279a4c336e.png">
<img width="1067" alt="Screenshot 2022-04-14 at 17 07 31" src="https://user-images.githubusercontent.com/6940726/163419762-4dd698e2-203e-443d-a38d-b7a075a3d9d0.png">

**Comment by enisdenjo** [comment]
@ollydixon the API never changed, [`onSubscribe` returns either an array of `GraphQLError`s or the `ExecutionArgs`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.ServerOptions.md#onsubscribe), you're not returning either.

**Comment by enisdenjo** [comment]
> For example where are you getting getDynamicContext from?

That's just an example of a function you can implement that returns the context dynamically from the arguments you pass in.

**Comment by ollydixon** [comment]
@enisdenjo thanks for the speedy reply, out full example doesn't seem to work though :-/

```
 // onConnect: async (connection) => {
  // const auth = connection?.connectionParams!["Authorization"] ?? "";
  // if (!auth) {
  //     return {};
  // }
  // // @ts-ignore
  // const user = await checkJwt(auth);
  // return { user };
  // },
  // @ts-ignore
  onSubscribe: async (ctx, msg, args) => {
      const auth = ctx?.connectionParams!["Authorization"] ?? "";
      const user = await checkJwt(auth);

      const newArgs: any = {
          schema,
          contextValue: ctx,
          operationName: msg.payload.operationName,
          document: parse(msg.payload.operationName),
          variableValues: msg.payload.variables,
          user,
      };

      return newArgs;
  },
```

**Comment by enisdenjo** [comment]
@ollydixon what does "doesn't seem to work" mean?

P.S. my example in https://github.com/enisdenjo/graphql-ws/issues/36#issuecomment-715285764 was wrong - it's fixed now.

**Comment by ollydixon** [comment]
@enisdenjo it throws an error

```
 onSubscribe: async (ctx, msg, args) => {
                const user = await checkJwt(ctx.connectionParams?.Authorization);
                return { ...args, contextValue: { user } };
            },
```

```Internal error occurred during message handling. Please check your implementation. TypeError: Cannot read properties of undefined (reading 'definitions')```

**Comment by enisdenjo** [comment]
I don't know what happened, but `onSubscribe` never had the `args` argument... Fixed https://github.com/enisdenjo/graphql-ws/issues/36#issuecomment-715285764 again.

Please consult the ["ws server and client auth usage with token expiration, validation and refresh" recipe](https://github.com/enisdenjo/graphql-ws#auth-token) instead.

Furthermore, if you still have errors being thrown - please provide the callstack too.

**Comment by hckr** [comment]
@ollydixon In your example, is `context` function called on client connection or on each subscription?

**Comment by ollydixon** [comment]
> @ollydixon In your example, is `context` function called on client connection or on each subscription?

We only subscribe once and send "events" to the client. Each event as a "type" and "object" that is parsed.

I wouldn't recommend having multiple subscriptions.

**Comment by hckr** [comment]
@ollydixon Right. But my specific question is does your code example handle the case in which a JWT token was valid when the client subscribed and then is expired after, let's say, 30 minutes – is the client disconnected / re-authenticated in any way?

**Comment by ollydixon** [comment]
@hckr Interesting edge case. The client will just reconnect then, once per hour blip. We have an event bus API that handles each device and potential missed socket events.

**Comment by ollydixon** [comment]
@hckr thanks, will do :-)

**Comment by enisdenjo** [comment]
I actually _don't_ recommend doing auth on each event emission because the amount of outgoing messages can grow real quick and soon you'll find yourself fighting with performance problems. The auth recipes has that approach displayed just as examples of what's possible.

IMHO it's perfectly fine to do auth either in `onConnect` or in `onSubscribe`.

As far as your concern about token expiry goes, @hckr, you can simply start a timer in `onConnect` set to run after the token expires which closes the connection forcing the client to re-connect and therefore re-authenticate.

I personally do it in `onSubscribe` with no extra steps. The WebSocket connection cannot be hijacked while active; meaning, it's safe to assume that even if the token expires, the originally authenticated user is still the same - which is enough for _me_.
